name: "encoon-development"
services:
  db:
    container_name: encoon-db-development
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - encoon
    configs:
      - source: db-init
        target: /docker-entrypoint-initdb.d/encoon-initdb.sql
    secrets:
      - db-password
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: encoon
      POSTGRES_DB: master
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
  apis:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.23.4
        WORKDIR /usr/src/encoon/apis
        CMD ["sh", "-c", "go run . -configuration ./testData/local-development.yml"]
    container_name: encoon-apis-development
    image: encoon-apis-development
    volumes:
      - ./apis:/usr/src/encoon/apis
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - encoon
    environment:
      - ENCOON_MOCK_DB_LOCALHOST=db
    depends_on:
      - db
  ui:
    build:
      context: .
      dockerfile_inline: |
        FROM node:22.12.0-alpine
        WORKDIR /usr/src/encoon/ui
        CMD ["sh", "-c", "npm install && npm run dev -- --host"]
    container_name: encoon-ui-development
    image: encoon-ui-development
    volumes:
      - ./ui:/usr/src/encoon/ui
    ports:
      - "5173:5173"
    networks:
      - encoon
  system-test:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.23.4
        WORKDIR /usr/src/encoon/apis
        COPY apis/go.mod apis/go.sum .
        RUN go mod download && go mod verify
    container_name: encoon-system-test
    image: encoon-system-test
    networks:
      - encoon
    environment:
      - ENCOON_MOCK_DB_LOCALHOST=db
      - ENCOON_KEEP_ALIVE_AFTER_SECONDS=900
    volumes:
      - ./:/usr/src/encoon
    depends_on:
      - db
    command: sh -c "./testData/run_all_tests.sh"
configs:
  encoon-configuration:
    file: ./testData/docker.testing.yml
  db-init:
    file: ./testData/docker.testing.sql
networks:
  encoon:
    driver: bridge
secrets:
  db-password:
    file: ./testData/.db_password
volumes:
  db:
    driver: local