#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/usr/src/encoon/frontend/node_modules/.pnpm/@sveltejs+kit@2.15.1_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.16.0_vite@6.0.6__svelte@5.16.0_vite@6.0.6/node_modules/@sveltejs/kit/node_modules:/usr/src/encoon/frontend/node_modules/.pnpm/@sveltejs+kit@2.15.1_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.16.0_vite@6.0.6__svelte@5.16.0_vite@6.0.6/node_modules/@sveltejs/node_modules:/usr/src/encoon/frontend/node_modules/.pnpm/@sveltejs+kit@2.15.1_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.16.0_vite@6.0.6__svelte@5.16.0_vite@6.0.6/node_modules:/usr/src/encoon/frontend/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/usr/src/encoon/frontend/node_modules/.pnpm/@sveltejs+kit@2.15.1_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.16.0_vite@6.0.6__svelte@5.16.0_vite@6.0.6/node_modules/@sveltejs/kit/node_modules:/usr/src/encoon/frontend/node_modules/.pnpm/@sveltejs+kit@2.15.1_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.16.0_vite@6.0.6__svelte@5.16.0_vite@6.0.6/node_modules/@sveltejs/node_modules:/usr/src/encoon/frontend/node_modules/.pnpm/@sveltejs+kit@2.15.1_@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.16.0_vite@6.0.6__svelte@5.16.0_vite@6.0.6/node_modules:/usr/src/encoon/frontend/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../svelte-kit.js" "$@"
else
  exec node  "$basedir/../../svelte-kit.js" "$@"
fi
