#  εncooη : data structuration, presentation and navigation.
#  Copyright David Lambert 2022

appName: "εncooη"
appTag: "Data structuration, presentation and navigation."

# Http Server configuration
httpServer:
  host: "localhost"
  port: 8080
  jwtExpiration: 120

# Database configuration
database:

- name: "test"
  host: "localhost"
  port: 5432
  user: "david.lambert"
  jwtsecret: "$2a$08$dcn22vRFIZmywvdYBFv5yORcOiGU.ZtqB9S1dTcxspVlzaelmZUPa"
  root: "root"
  password: "$2a$08$40D/LcEidSirsqMSQcfc9.DAPTBOpPBelNik5.ppbLwSodxczbNWa"
  testSleepTime: 500
  timeOutThreshold: 1000

- name: "sandbox"
  host: "localhost"
  port: 5432
  user: "david.lambert"
  jwtsecret: "$2a$08$DO1mR4Iu33zJ/UidByyUJOSd6WmrMT.b0Nvna414pS4s24oHlRbNq"
  root: "root"
  password: "$2a$08$40D/LcEidSirsqMSQcfc9.DAPTBOpPBelNik5.ppbLwSodxczbNWa"
  timeOutThreshold: 1000
