#  εncooη : data structuration, presentation and navigation.
#  Copyright David Lambert 2022

appName: "εncooη" # Application name to be displayed
appTag: "Data structuration, presentation and navigation." # Application tag to be displayed

log: true
trace: false
showTiming: true

gridCacheSize: 500

# Http Server configuration
httpServer:
  port: 8080
  jwtExpiration: 120 # Expiration (in minutes) of the JSON Web Token

# Database configuration
database:

- name: "master"
  host: "localhost"
  port: 5432
  user: "david.lambert"
  jwtsecret: "$2a$08$DO1mR4Iu33zJ/UidByyUJOSd6WmrMT.b0Nvna414pS4s24oHlRbNq"
  root: "root"
  password: "$2a$08$40D/LcEidSirsqMSQcfc9.DAPTBOpPBelNik5.ppbLwSodxczbNWa"
  timeOutThreshold: 500

- name: "test"
  host: "localhost"
  port: 5432
  user: "david.lambert"
  jwtsecret: "$2a$08$dcn22vRFIZmywvdYBFv5yORcOiGU.ZtqB9S1dTcxspVlzaelmZUPa"
  root: "root"
  password: "$2a$08$40D/LcEidSirsqMSQcfc9.DAPTBOpPBelNik5.ppbLwSodxczbNWa"
  testSleepTime: 1000
  timeOutThreshold: 2000

- name: "sandbox"
  host: "localhost"
  port: 5432
  user: "david.lambert"
  jwtsecret: "$2a$08$DO1mR4Iu33zJ/UidByyUJOSd6WmrMT.b0Nvna414pS4s24oHlRbNq"
  root: "root"
  password: "$2a$08$40D/LcEidSirsqMSQcfc9.DAPTBOpPBelNik5.ppbLwSodxczbNWa"
  timeOutThreshold: 500
