version: "3.9"
name: "encoon-sandbox"
services:
  db:
    container_name: encoon-db-sandbox
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - encoon-sandbox
    configs:
      - source: db-init
        target: /docker-entrypoint-initdb.d/encoon-initdb.sql
    secrets:
      - db-password
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: encoon
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
  web:
    container_name: encoon-sandbox
    image: encoon
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - encoon-sandbox
    configs:
      - source: encoon-configuration
        target: /usr/encoon/configuration.yml
    depends_on:
      - db
configs:
  encoon-configuration:
    file: ./testData/docker.sandbox.yml
  db-init:
    file: ./testData/docker.sandbox.sql
networks:
  encoon-sandbox:
    driver: bridge
secrets:
  db-password:
    file: ./testData/.db_password.sandbox
volumes:
  db:
    driver: local