version: "3.9"
name: "encoon"
services:
  encoon-db:
    container_name: encoon-db
    image: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - encoon-network
    environment:
      POSTGRES_USER: "encoon"
      POSTGRES_PASSWORD: "encoon"
      POSTGRES_DB: "test"
  encoon-web:
    build: .
    container_name: encoon-web
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - encoon-network
    configs:
      - source: encoon-configuration
        target: /usr/encoon/configuration.yml
    depends_on:
      - encoon-db
  encoon-test:
    build:
      context: .
      dockerfile: ./Dockerfile-systemTest
    container_name: encoon-test
    networks:
      - encoon-network
    environment:
      - ENCOON_MOCK_DB_LOCALHOST=encoon-db
      - ENCOON_KEEP_ALIVE_AFTER_SECONDS=1800
    command: sh -c "./testData/run_all_tests.sh"
configs:
  encoon-configuration:
    file: ./testData/docker-testing.yml
networks:
  encoon-network:
    driver: bridge
