version: "3.9"
name: "encoon-development"
services:
  db:
    container_name: db
    image: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - encoon-network
    configs:
      - source: db-init
        target: /docker-entrypoint-initdb.d/docker.testing.sql
    secrets:
      - db-password
    environment:
      POSTGRES_USER: "encoon"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
  web:
    build: .
    container_name: web
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - encoon-network
    configs:
      - source: encoon-configuration
        target: /usr/encoon/configuration.yml
    depends_on:
      - db
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.systemTest
    container_name: test
    networks:
      - encoon-network
    environment:
      - ENCOON_MOCK_DB_LOCALHOST=db
      - ENCOON_KEEP_ALIVE_AFTER_SECONDS=900
    depends_on:
      - db
    command: sh -c "./testData/run_all_tests.sh"
configs:
  encoon-configuration:
    file: ./testData/docker.testing.yml
  db-init:
    file: ./testData/docker.testing.sql
networks:
  encoon-network:
    driver: bridge
secrets:
  db-password:
    file: ./testData/.db_password