#  εncooη : data structuration, presentation and navigation.
#  Copyright David Lambert 2022

# Http Server configurations
httpServer:
    host: "localhost"
    port: 8080
    jwtExpiration: 120

appName: "εncooη"
appTag: "Data structuration, presentation and navigation."
timeOutThreshold: 1000